### ISSUE TITLE
Internationalize app

### ISSUE THREAD

**Issue by uo288347** [Arquisoft/wiq_es04a#128]

**Comment by PabloGOP** [comment]
From #270 
## Status
As for now, I think every page and test is up-to-date excepting:
- Instructions
- Homepage

As these require special treatment as long as they use data from an external source.

## How to use
#### In pages in which internationalization is being applied:
- Call t("`key_of_jsons_message`") whenever you want to insert a string
- Make sure `key_of_jsons_message` is properly setted in all the `webapp/src/localize/*.json` files

#### In pages in which internationalization is NOT being applied:
- Import `useTranslation`
- Define in the component `t`: `const { t } = useTranslation();`
- See previous entry

**Comment by PabloGOP** [comment]
I keep it open to remember:
- Inter missing pages
- Question generation has to be leveraged
